var permuter = {
  "MADRID-CHAMARTÍN-CLARA CA": "MADRID",
  "MADRID-PRINCIPE PIO": "MADRID",
  "MADRID-ATOCHA-ALMUDENA GR": "MADRID",
  "VALENCIA-JOAQUIN-SOROLLA": "VALENCIA",
  "Valencia Joaquín Sorolla": "VALENCIA",
};
