var testData = [
  // SIMPLE TRIP
  {
    title: "Train to MADRID-CHAMARTÍN-CLARA CA",
    startTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 155 * 60 * 1000),
    location: "SALAMANCA",
    description: "This is an automatically event generated by testSuite",
  },
  {
    title: "Train to SALAMANCA",
    startTime: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 250 * 60 * 1000),
    endTime: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 360 * 60 * 1000),
    location: "MADRID-CHAMARTÍN-CLARA CA",
    description: "This is an automatically event generated by testSuite",
  },
];

/**
 * Create test suite with testData
 */
function addTestEvents() {
  for (var testIndex in testData) {
    let test = testData[testIndex];
    sourceCalendar.createEvent(test.title, test.startTime, test.endTime, {
      location: test.location,
      description: test.description,
    });
  }
}
